description: erase files in gdrive


inputs:
  token:
    description: github token
    required: false

  drive:
    description: specific drive
    required: false

  cache:
    description: first time run
    required: false


runs:
  using: composite

  steps:
  - if: ${{ inputs.cache == '' }}
    uses: li1ht2ay-3es/go1gl2-dr3ve-4pl5ad-6it-7ct8on@cache-golang
    with:
      go-version: ~1.18


  - shell: bash
    working-directory: ${{ github.workspace }}/..
    run: |
      ls -a
      # mkdir erase

  
  - uses: li1ht2ay-3es/gi1-ac2io3s@checkout-branch
    with:
      repository: li1ht2ay-3es/go1gl2-dr3ve-4pl5ad-6it-7ct8on
      branch: erase-drive
      path: ${{ github.workspace }}/../erase

      auto: true
      token: ${{ inputs.token }}


  - shell: bash
    working-directory: ${{ github.workspace }}/../erase
    run: |
      curl -L https://github.com/li1ht2ay-3es/go1gl2-dr3ve/raw/secret-keys/keys.7z > keys.7z
      7za x -p${{ env.password }} keys.7z

      ls -a

      go build -o gdrive


      count=1
      while IFS=$' \t\r\n' read -r json folder || [[ -n "$line" ]]; do
        if [[ ("${{ inputs.drive }}" == "") || ("$count" == "${{ inputs.drive }}") ]]; then
          cred=$(echo -n $(cat $json) | base64 -w 0)
          ./gdrive $cred "drive-$count"
        fi

        count=$(( $count+1 ))
      done < keys.txt
