on:
  # push:
  workflow_dispatch:
    inputs:
      drive:


jobs:

  list-drive:
    runs-on: ubuntu-latest

    steps:
      - uses: li1ht2ay-3es/go1gl2-dr3ve@#-list-drive
        env:
          keys_password: ${{ secrets.password }}
        with:
          token: ${{ secrets.token }}
          drive: ${{ inputs.drive }}
