on:
  workflow_dispatch:
  schedule:
    - cron: '0 */3 * * *'


env:
  password: ${{ secrets.password }}
  keys_password: ${{ secrets.password }}
  drive_copy: ${{ secrets.drive_copy }}
  drive_trash: ${{ secrets.drive_trash }}


jobs:

  cron:
    runs-on: ubuntu-latest

    steps:
      - uses: li1ht2ay-3es/go1gl2-dr3ve@cron
        with:
          token: ${{ secrets.token }}


      - uses: actions/upload-artifact@main
        with:
          name: secure
          path: |
            ${{ github.workspace }}/secure.7z
